name: Deploy to ECS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ALB_URL: http://alb-ecs-hello-world-943339392.us-east-1.elb.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: arn:aws:iam::624012998763:role/github-actions-ecs-oidc-role
        aws-region: us-east-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      run: |
        docker build -t ecs-hello-world ./app
        docker tag ecs-hello-world:latest 624012998763.dkr.ecr.us-east-1.amazonaws.com/ecs-hello-world:latest
        docker push 624012998763.dkr.ecr.us-east-1.amazonaws.com/ecs-hello-world:latest

    - name: Force ECS deployment
      run: |
        aws ecs update-service \
          --cluster ecs-hello-world-cluster-nv \
          --service ecs-hello-world-task-nv-service-6e5uwloj \
          --force-new-deployment

    - name: Integration test - check ALB endpoint
      run: |
       echo "Waiting for ECS service to stabilize..."
       sleep 30

        echo "=== Test 1: Root endpoint returns 200 ==="
        STATUS_CODE=$(curl -k -s -L -o /dev/null -w "%{http_code}" $ALB_URL)

        echo "ALB returned status code: $STATUS_CODE"

        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "Integration test failed: ALB did not return 200"
          exit 1
        fi

        echo "Integration test passed"
        
        RESPONSE=$(curl -k -s -L $ALB_URL)

        echo "Response: $RESPONSE"

        echo "$RESPONSE" | grep -q "Hello" || exit 1

        echo "=== Test 2: ALB rule blocks forbidden path ==="
        if [ "$STATUS_CODE" -ne 403 ]; then
        echo "‚ùå Forbidden rule failed (expected 403)"
        exit 1
        fi

        echo "‚úÖ Forbidden path rule passed"

        echo "=== Test 3: Redirect rule works ==="
        STATUS_CODE=$(curl -k -s -o /dev/null -w "%{http_code}" "$ALB_URL/redirect-test")
        echo "Status code: $STATUS_CODE"

        if [ "$STATUS_CODE" -ne 301 ]; then
          echo "‚ùå Redirect rule failed (expected 301)"
          exit 1
        fi

        echo "‚úÖ Redirect rule passed"

        echo "=== Test 4: WAF blocks request with header ==="
        STATUS_CODE=$(curl -k -s -H "X-Test-Block: true" -o /dev/null -w "%{http_code}" "$ALB_URL/")
        echo "Status code: $STATUS_CODE"

        if [ "$STATUS_CODE" -ne 403 ]; then
          echo "‚ùå WAF header block failed (expected 403)"
          exit 1
        fi

        echo "‚úÖ WAF rule passed"

        echo "üéâ All integration tests passed"